# Generated by Django 5.0.7 on 2024-07-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="описание"),
                ),
                ("photo", models.ImageField(upload_to="news", verbose_name="фото")),
                (
                    "create_data",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата новостей"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Настройка новостей",
            },
        ),
    ]
